# Default values for entigo-training-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.infralib.learn.entigo.io/test/
  pullPolicy: IfNotPresent

ingress:
  hostname: ""
  
api:
  replicaCount: 3
  image: api:v1
  redisHost: api-redis-master
  imgHost: img
  sessionSecret: ChangeMe
  db:
    host: db
    user: api_user
    pass: SuperSecret123
    name: formdb
  
img:
  replicaCount: 1
  image: img:v2
  diskSize: 100Gi
  diskType: gp3

web:
  replicaCount: 3
  image: web:v1

form:
  replicaCount: 2
  image: form:v1
  db:
    user: form_user
    pass: FormSecret

dbupdate:
  image: db:v2
  db:
    user: db_user
    pass: DbUpdateSecret
    
db:
  image: library/mariadb:10.6
  rootPass: VeryImportantSecret


redis:
  replica:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 1024Mi
        cpu: 1
        ephemeral-storage: 1024Mi
  master: 
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 1024Mi
        cpu: 1
        ephemeral-storage: 1024Mi


