# Default values for entigo-training-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.infralib.learn.entigo.io/test/
  pullPolicy: IfNotPresent

ingress:
  hostname: ""

db:
  host: ""
  name: ""

api:
  replicaCount: 2
  image: api:v1

web:
  replicaCount: 2
  image: web:v1

form:
  replicaCount: 2
  image: form:v1

dbupdate:
  image: db:v1

redis:
  replica:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 1024Mi
        cpu: 1
        ephemeral-storage: 1024Mi
  master: 
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 1024Mi
        cpu: 1
        ephemeral-storage: 1024Mi


