apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
  labels:
    category: application
data:
  DB_HOST: {{ .Values.api.db.host }}
  DB_NAME: {{ .Values.api.db.name }}
  IMAGE_HOST: {{ .Values.api.imgHost }}
  
