
apiVersion: batch/v1
kind: Job
metadata:
  name: db-update
  labels:
    category: application
spec:
  #Once a Job reaches activeDeadlineSeconds, all of its running Pods are terminated and the Job status will become type: Failed with reason: DeadlineExceeded.
  activeDeadlineSeconds: 600
  #Keep 1 pods running.
  parallelism: 1
  #Need to make 1 time finish
  completions: 1
  template:
    spec:
      containers:
      - name: python
        image: {{ .Values.image.repository }}{{ .Values.dbupdate.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["yoyo"]
        args: [ "apply" ]
        envFrom:
          - configMapRef:
              name: conf
          - secretRef:
              name: db
      restartPolicy: Never
  # There are situations where you want to fail a Job after some amount of retries due to a logical error in configuration etc.
  backoffLimit: 10
