apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeobjectstoragebuckets.entigo.io
  annotations:
      argocd.argoproj.io/sync-wave: "-4"
spec:
  group: entigo.io
  names:
    kind: CompositeObjectStorageBucket
    plural: compositeobjectstoragebuckets
  claimNames:
    kind: ObjectStorageBucket
    plural: objectstoragebuckets
  connectionSecretKeys:
    - account_id
    - account_key
    - bucket_name
    - bucket_region
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  # The full name of the bucket
                  name:
                    type: string
                required:
                  - name
            required:
              - parameters

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: privates3objectstoragebucket
  annotations:
      argocd.argoproj.io/sync-wave: "-3"
  labels:
    provider: aws
    # Could have multiple classes, for different purposes
    class: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: entigo.io/v1alpha1
    kind: CompositeObjectStorageBucket
  resources:
    - base:
        # See s3 bucket API ref: https://doc.crds.dev/github.com/crossplane/provider-aws/s3.aws.crossplane.io/Bucket/v1beta1@v0.19.0
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            acl: "private"
            locationConstraint: eu-north-1
            objectOwnership: BucketOwnerPreferred
            publicAccessBlockConfiguration:
              blockPublicPolicy: true
              blockPublicAcls: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            accelerateConfiguration:
              status: Enabled
            versioningConfiguration:
              status: Suspended
            serverSideEncryptionConfiguration:
              rules:
              - applyServerSideEncryptionByDefault:
                  sseAlgorithm: AES256
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
        # Write the bucket information to a secret called: {bucket_name}-connection-details
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-connection-details"
      connectionDetails:
        # The resulting secret contains a bucket_name key
        # This key contains the value that was generated by the bucket resource in the endpoint key
        - name: bucket_name
          fromConnectionSecretKey: endpoint
        - name: bucket_region
          fromConnectionSecretKey: region
          
    - base:
        # See IamPolicy Api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMPolicy/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            path: "/"
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        # We suffix it with '-bucket-access-policy'
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        # Use the bucket name + the '-bucket-access-policy' suffix
        # This will be the resulting name in aws
        # Each bucket name must be unique, so this in turn will be unique
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.description"
          transforms:
          - type: string
            string:
              fmt: "Policy for access to the %s bucket"
        # CombineForComposite works just like the string transforms above
        # Except we can define multiple placeholders in the fmt
        # We need crossplane >= 1.3.0 for this feature
        - type: CombineFromComposite
          toFieldPath: "spec.forProvider.document"
          policy:
            fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.name
              - fromFieldPath: spec.parameters.name
            strategy: string
            # This policy gives a user full access to the bucket and bucket objects
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": ["s3:*"],
                      "Resource": [
                        "arn:aws:s3:::%s"
                      ]
                    },
                    {
                      "Effect": "Allow",
                      "Action": [
                        "s3:*"
                      ],
                      "Resource": [
                        "arn:aws:s3:::%s",
                        "arn:aws:s3:::%s/*"
                      ]
                    }
                  ]
                }
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-policy-details"
    - base:
        # See IamUser api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMUser/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: User
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            path: "/"
      patches:
        # Use bucket name suffixed with '-user'
        # This will be the username of the iam account in AWS
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-details"
    - base:
        # See IamUserPolicyAttachment api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMUserPolicyAttachment/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: UserPolicyAttachment
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          writeConnectionSecretToRef:
            namespace: crossplane-system
          # The contents of this are patched in below
          forProvider: {}
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-bucket-policy"
        # Reference the policy we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.policyArnRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-bucket-access-policy"
        # Reference the user we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.userNameRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-policy-details"
    - base:
        # See IAMAccessKey api ref: https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/IAMAccessKey/v1alpha1@v0.19.0
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: AccessKey
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider: {}
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-access-key"
        # Reference the user we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.userNameRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-user-access-key"
      connectionDetails:
        # We take the username key from the access key and set it to the account_id in the resulting secret
        - name: account_id
          fromConnectionSecretKey: username
        # We take the password key from the access key and set it to the account_key in the resulting secret
        - name: account_key
          fromConnectionSecretKey: password
---
apiVersion: entigo.io/v1alpha1
kind: ObjectStorageBucket
metadata:
  name: img
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  parameters:
    # You would need to change this to something unique
    name: "entigotrainingimgasd"
  compositionSelector:
    matchLabels:
      provider: aws
      class: default
  writeConnectionSecretToRef:
    name: img

---
apiVersion: v1
kind: Service
metadata:
  name: img
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3003
  selector:
    app: img
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: img
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app: img
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: img
  labels:
    category: application
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: img
  template:
    metadata:
      labels:
        app: img
        category: database
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: img
              topologyKey: kubernetes.io/hostname
      containers:
      - name: golang
        image: {{ .Values.image.repository }}{{ .Values.img.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          tcpSocket:
            port: 3003
          initialDelaySeconds: 5
          timeoutSeconds: 15
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 3003
          name: http-img
        env:
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: img
              key: bucket_region
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: img
              key: account_id
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: img
              key: account_key
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: img
              key: bucket_name
