apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeobjectstoragebuckets.entigo.io
  annotations:
      argocd.argoproj.io/sync-wave: "-4"
spec:
  group: entigo.io
  names:
    kind: CompositeObjectStorageBucket
    plural: compositeobjectstoragebuckets
  claimNames:
    kind: ObjectStorageBucket
    plural: objectstoragebuckets
  connectionSecretKeys:
    - account_id
    - account_key
    - bucket_name
    - bucket_region
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  # The full name of the bucket
                  name:
                    type: string
                required:
                  - name
            required:
              - parameters

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: privates3objectstoragebucket
  annotations:
      argocd.argoproj.io/sync-wave: "-3"
  labels:
    provider: aws
    # Could have multiple classes, for different purposes
    class: default
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: entigo.io/v1alpha1
    kind: CompositeObjectStorageBucket
  resources:
    # Main S3 Bucket
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider:
            forceDestroy: true  # This enables force deletion of non-empty buckets
            region: eu-north-1
            tags:
              created-by: "crossplane-composition"
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
          - type: string
            string:
              fmt: "%s-connection-details"
      connectionDetails:
        - name: bucket_name
          fromConnectionSecretKey: id
        - name: bucket_region
          fromConnectionSecretKey: region

    # Bucket Ownership Controls
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketOwnershipControls
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          forProvider:
            rule:
            - objectOwnership: BucketOwnerPreferred
            region: eu-north-1
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.bucket"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-ownership"

    # Public Access Block Configuration
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketPublicAccessBlock
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          forProvider:
            blockPublicPolicy: true
            blockPublicAcls: true
            ignorePublicAcls: true
            restrictPublicBuckets: true
            region: eu-north-1
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.bucket"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-public-access-block"

    # Accelerate Configuration
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketAccelerateConfiguration
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          forProvider:
            status: Enabled
            region: eu-north-1
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.bucket"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-accelerate"

    # Versioning Configuration
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketVersioning
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          forProvider:
            versioningConfiguration:
            - status: Suspended
            region: eu-north-1
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.bucket"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-versioning"

    # Server Side Encryption Configuration
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketServerSideEncryptionConfiguration
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          forProvider:
            rule:
            - applyServerSideEncryptionByDefault:
              - sseAlgorithm: AES256
            region: eu-north-1
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.bucket"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-encryption"

    # Bucket ACL (Private)
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketAcl
        spec:
          deletionPolicy: Delete
          providerConfigRef:
            name: crossplane-aws
          forProvider:
            acl: private
            region: eu-north-1
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.bucket"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              fmt: "%s-acl"
---
apiVersion: entigo.io/v1alpha1
kind: ObjectStorageBucket
metadata:
  name: img
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    # You would need to change this to something unique
    name: "entigo-training-img-{{ randAlphaNum 10 | lower }}"
  compositionSelector:
    matchLabels:
      provider: aws
      class: default
  writeConnectionSecretToRef:
    name: img

---
apiVersion: v1
kind: Service
metadata:
  name: img
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3003
  selector:
    app: img
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: img
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: external
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
spec:
  ingressClassName: alb
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /img
        pathType: Prefix
        backend:
          service:
            name: img
            port: 
              number: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: img
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app: img
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: img
  labels:
    category: application
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: img
  template:
    metadata:
      labels:
        app: img
        category: database
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: img
              topologyKey: kubernetes.io/hostname
      containers:
      - name: golang
        image: {{ .Values.image.repository }}{{ .Values.img.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          tcpSocket:
            port: 3003
          initialDelaySeconds: 5
          timeoutSeconds: 15
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 3003
          name: http-img
        env:
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: img
              key: bucket_region
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: img
              key: account_id
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: img
              key: account_key
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: img
              key: bucket_name
