apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    category: application
data:
  SESSION_SECRET: {{ .Values.api.sessionSecret | b64enc | quote }}
  DB_PASSWORD: {{ .Values.api.db.pass | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: form
  labels:
    category: application
data:
  DB_PASSWORD: {{ .Values.form.db.pass | b64enc | quote }}
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-update
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets-dev
    kind: ClusterSecretStore
  target:
    name: db-update
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "dev-infra-database-database"
      property: password
  - secretKey: DB_USER
    remoteRef:
      key: "dev-infra-database-database"
      property: username
  - secretKey: DB_NAME
    remoteRef:
      key: "dev-infra-database-database"
      property: dbname
