apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    category: application
data:
  SESSION_SECRET: {{ .Values.api.sessionSecret | b64enc | quote }}
  DB_PASSWORD: {{ .Values.api.db.pass | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: form
  labels:
    category: application
data:
  DB_PASSWORD: {{ .Values.form.db.pass | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db
  labels:
    category: database
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootPass | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-update
  labels:
    category: database
data:
  DB_PASSWORD: {{ .Values.dbupdate.db.pass | b64enc | quote }} 

