apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    category: application
data:
  SESSION_SECRET: {{ randAlphaNum 20 | b64enc }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets-dev
    kind: ClusterSecretStore
  target:
    name: db
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "dev-infra-database-database"
      property: password
  - secretKey: DB_USER
    remoteRef:
      key: "dev-infra-database-database"
      property: username

