apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    category: application
data:
  SESSION_SECRET: {{ .Values.api.sessionSecret | b64enc | quote }}
  DB_PASSWORD: {{ .Values.api.db.pass | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: form
  labels:
    category: application
data:
  DB_PASSWORD: {{ .Values.form.db.pass | b64enc | quote }}
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-update
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets-dev
    kind: ClusterSecretStore
  target:
    name: db-update
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "{{ .Values.environment }}.password"
  - secretKey: DB_USER
    remoteRef:
      key: "{{ .Values.environment }}.username"
  - secretKey: DB_NAME
    remoteRef:
      key: "{{ .Values.environment }}.dbname"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
data:
  initdb.sql: |
    SET character_set_server = 'utf8mb4';
    SET collation_server = 'utf8mb4_estonian_ci';
    -- Loome andmebaasi, mis kasutab utf8 kodeeringut
    CREATE OR REPLACE DATABASE formdb CHARACTER SET = 'utf8mb4' COLLATE = 'utf8mb4_estonian_ci';

    -- Loome superuseri, mis tegeleb andmebaasi migratsioonidega
    CREATE USER '{{ .Values.dbupdate.user }}'@'%' IDENTIFIED BY '{{ .Values.dbupdate.db.pass }}';
    -- Loome piiratud õigustega kasutaja, mida kasutab api andmebaasiga suhtlemiseks
    CREATE USER '{{ .Values.api.user }}'@'%' IDENTIFIED BY '{{ .Values.api.db.pass }}';
    -- Loome piiratud kasutaja, mida kasutab postistuste salvestaja
    CREATE USER '{{ .Values.form.user }}'@'%' IDENTIFIED BY '{{ .Values.form.db.pass';

    -- Anname db_user'ile kõik õigused formdbe andmebaasile
    GRANT ALL PRIVILEGES ON formdb.* TO '{{ .Values.dbupdate.user }}'@'%' WITH GRANT OPTION;
    -- Anname api_user'ile lugemise õigused andmebaasile
    GRANT SELECT ON formdb.* TO '{{ .Values.api.user }}'@'%';
    -- Anname api_user'ile lugemise õigused andmebaasile
    GRANT SELECT ON formdb.* TO '{{ .Values.form.user }}'@'%';

    -- Värskendame muudetud õigused
    FLUSH PRIVILEGES;
    USE formdb;
    -- Muudame ühenduse kodeeringut, vastasel juhul Docker võib vaikimisi kasutada vale kodeeringut
    SET names 'utf8mb4';
    -- Loome esimese tabeli
    CREATE TABLE advertisement (
      id INT AUTO_INCREMENT PRIMARY KEY,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT (UTC_TIMESTAMP)
    );
    GRANT INSERT, UPDATE ON advertisement TO '{{ .Values.form.user }}'@'%';

